### ISSUE TITLE
[urgent] Leaking previous pastes?

### ISSUE THREAD

**Issue by Nic321** [ptpb/pb#189] opened 2017-05-21 15:05 UTC
Pretty sure this isn't supposed to happen:

https://ptpb.pw/.ssh

https://ptpb.pw/.svg

https://ptpb.pw/.svn

Is there a quick fix?

**Comment by buhman** [comment] 2017-05-21 22:09
Nice.

```
λ zack [~] → curl -X REPORT https://ptpb.pw/.ssh
date: 2016-05-11T07:32:39.576000+00:00
digest: 17e0a67cb77f4d88f24de722e6e9e69c6c509276
long: ABfgpny3f02I8k3nIubp5pxsUJJ2
short: UJJ2
size: 64855
status: found
url: https://ptpb.pw/UJJ2
```

**Comment by buhman** [comment] 2017-05-21 22:57
> Is there a quick fix?

This is something like a three-part bug:

 * `.ssh` is a theoretically valid paste name according to the sid [regex](https://github.com/ptpb/pb/blob/master/pb/converters.py#L44) (incorrect? behavior)
* `urlsafe_b64decode('.ssh')` throws `binascii.Error('Incorrect padding')` (expected? behavior)
* the view does not validate the correctness of converter result, so it assumes `None` to be a valid paste sid value (indeterminate behavior)
* the view then generates the following query (correct behavior)
  * `{'short': None, 'private': {'$exists': False}, 'namespace': {'$exists': False}}`
* [paste.model._transform](https://github.com/ptpb/pb/blob/master/pb/paste/model.py#L23) helpfully transforms the query to:
  * `{'private': {'$exists': False}, 'namespace': {'$exists': False}}` (unexpected behavior)

The resulting cursor represents all non-private pastes that are in the global namespace, sorted by creation date. The resulting response is "the most recent non-private paste in the global namespace".

Additional bugs:

 * I call `cur.count()` which results in mongo evaluating the result of the entire query (slow). The correct thing to do is catch `StopIteration` on `next(cur)`

**Comment by buhman** [comment] 2017-05-21 23:01
This is actually easy to fix. I don't remember the historical reasons for the character group `[A-Za-z0-9_~.-]` (actually I do, it was for the previous `base66` scheme), but `~.` are not part of python's `urlsafe` alphabet.

**Comment by buhman** [comment] 2017-05-21 23:06
Fixed in https://github.com/ptpb/pb/commit/488ecea135e90e59029b8728e9aebe71bd137789.

**Comment by buhman** [comment] 2017-05-21 23:14
The example URLs now return flask 404 responses.

**Closed by buhman** 2017-05-21 23:14 UTC
Labels: bug, information-leakage

**Comment by buhman** [comment] 2017-05-21 23:33
> the most recent

Also notice how `-X REPORT` returned https://ptpb.pw/UJJ2, the least recent paste in the production pb database (created by me), instead of the most recent. This is because sorting by `date` is not applied correctly to all `find()` queries, including the one the report view uses.

**Comment by buhman** [comment] 2017-05-21 23:43
> represents all non-private pastes

I tested this again with 488ecea removed, and it was also possible to access private pastes with a url like this:

`https://ptpb.pw/.aaaaaaaaaaaaaaaaaaaaaaaaaaa`
